[package]
name = "cga_artifact"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
bpaf = { version = "0.7.7", features = ["derive"] }
cgmath = "0.18.0"
env_logger = "0.9"
log = "0.4"